install.packages('devtools')
install.packages('tidyverse')
install.packages('shiny')
install.packages('readxl')
install.packages('tidyr')
install.packages('dplyr')
install.packages('ggplot2')
install.packages('vegan')
install.packages('pheatmap')
install.packages('openxlsx')
install.packages("BiocManager")

require('BiocManager')
BiocManager::install("DESeq2")
BiocManager::install("piano")
BiocManager::install("phyloseq")
BiocManager::install("microbiome")
