install.packages('devtools')
install.packages('tidyverse')
install.packages('shiny')
install.packages('readxl')
install.packages('tidyr')
install.packages('dplyr')
install.packages('ggplot2')
install.packages('vegan')
install.packages('pheatmap')
install.packages('openxlsx')
install.packages("BiocManager")

#TO check if all packages are installed successfully
require('devtools')
require('tidyverse')
require('shiny')
require('readxl')
require('tidyr')
require('dplyr')
require('ggplot2')
require('vegan')
require('pheatmap')
require('openxlsx')
require("BiocManager")

require('BiocManager')
BiocManager::install("DESeq2")
BiocManager::install("piano")
BiocManager::install("phyloseq")
BiocManager::install("microbiome")
